# Generated by Django 4.2.5 on 2023-10-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_evento_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas_eventos/'),
        ),
    ]
